"""add_drug_interaction_ml_system

Revision ID: a92edf2cf810
Revises: e3dc80b5c221
Create Date: 2026-05-09 15:23:05.968765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a92edf2cf810'
down_revision: Union[str, Sequence[str], None] = 'e3dc80b5c221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug_event_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drug_event_types_event_name'), 'drug_event_types', ['event_name'], unique=True)
    op.create_table('drug_features',
    sa.Column('drug_id', sa.String(length=50), nullable=False),
    sa.Column('targets', sa.Text(), nullable=True),
    sa.Column('enzymes', sa.Text(), nullable=True),
    sa.Column('pathways', sa.Text(), nullable=True),
    sa.Column('smiles', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drug_id'], ['drugs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('drug_id')
    )
    op.drop_index(op.f('ix_drug_atc_codes_code'), table_name='drug_atc_codes')
    op.drop_index(op.f('ix_drug_categories_name'), table_name='drug_categories')
    op.add_column('drug_interactions', sa.Column('event_type_id', sa.Integer(), nullable=True))
    op.add_column('drug_interactions', sa.Column('interaction_label', sa.String(length=255), nullable=True))
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'interactionsource') THEN CREATE TYPE interactionsource AS ENUM ('database', 'model_predicted'); END IF; END $$")
    op.add_column('drug_interactions', sa.Column('source', sa.Enum('database', 'model_predicted', name='interactionsource'), nullable=True))
    op.add_column('drug_interactions', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.drop_index(op.f('ix_drug_interactions_with_id'), table_name='drug_interactions')
    op.create_index(op.f('ix_drug_interactions_event_type_id'), 'drug_interactions', ['event_type_id'], unique=False)
    op.create_index(op.f('ix_drug_interactions_interaction_label'), 'drug_interactions', ['interaction_label'], unique=False)
    op.create_index(op.f('ix_drug_interactions_interacts_with_id'), 'drug_interactions', ['interacts_with_id'], unique=False)
    op.create_index(op.f('ix_drug_interactions_source'), 'drug_interactions', ['source'], unique=False)
    op.create_foreign_key(None, 'drug_interactions', 'drug_event_types', ['event_type_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_drugs_name'), table_name='drugs')
    op.create_index(op.f('ix_drugs_generic_name'), 'drugs', ['generic_name'], unique=False)
    op.alter_column('prescription_items', 'drug_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.drop_constraint(op.f('user_health_baselines_user_id_key'), 'user_health_baselines', type_='unique')
    op.drop_index(op.f('ix_user_health_baselines_user_id'), table_name='user_health_baselines')
    op.create_index(op.f('ix_user_health_baselines_user_id'), 'user_health_baselines', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_health_baselines_user_id'), table_name='user_health_baselines')
    op.create_index(op.f('ix_user_health_baselines_user_id'), 'user_health_baselines', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('user_health_baselines_user_id_key'), 'user_health_baselines', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('prescription_items', 'drug_id',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_drugs_generic_name'), table_name='drugs')
    op.create_index(op.f('ix_drugs_name'), 'drugs', ['generic_name'], unique=False)
    op.drop_constraint(None, 'drug_interactions', type_='foreignkey')
    op.drop_index(op.f('ix_drug_interactions_source'), table_name='drug_interactions')
    op.drop_index(op.f('ix_drug_interactions_interacts_with_id'), table_name='drug_interactions')
    op.drop_index(op.f('ix_drug_interactions_interaction_label'), table_name='drug_interactions')
    op.drop_index(op.f('ix_drug_interactions_event_type_id'), table_name='drug_interactions')
    op.create_index(op.f('ix_drug_interactions_with_id'), 'drug_interactions', ['interacts_with_id'], unique=False)
    op.drop_column('drug_interactions', 'confidence_score')
    op.drop_column('drug_interactions', 'source')
    op.execute("DROP TYPE IF EXISTS interactionsource")
    op.drop_column('drug_interactions', 'interaction_label')
    op.drop_column('drug_interactions', 'event_type_id')
    op.create_index(op.f('ix_drug_categories_name'), 'drug_categories', ['category_name'], unique=False)
    op.create_index(op.f('ix_drug_atc_codes_code'), 'drug_atc_codes', ['atc_code'], unique=False)
    op.drop_table('drug_features')
    op.drop_index(op.f('ix_drug_event_types_event_name'), table_name='drug_event_types')
    op.drop_table('drug_event_types')
    # ### end Alembic commands ###
